//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistanceDetail
    {
        public int AssistanceDetailID { get; set; }
        public Nullable<int> AssistanceID { get; set; }
        public Nullable<int> Technician { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Report { get; set; }
    
        public virtual Assistance Assistance { get; set; }
        public virtual Technicians Technicians { get; set; }
    }
}
