//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractAssets = new HashSet<ContractAssets>();
            this.Assistance = new HashSet<Assistance>();
        }
    
        public int ContractID { get; set; }
        public Nullable<int> Process { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOfOpen { get; set; }
        public Nullable<System.DateTime> DateOfClose { get; set; }
        public Nullable<int> Technician { get; set; }
        public string Status { get; set; }
    
        public virtual Process Process1 { get; set; }
        public virtual Technicians Technicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAssets> ContractAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assistance> Assistance { get; set; }
    }
}
