//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAssets
    {
        public int ContractID { get; set; }
        public int AssetID { get; set; }
        public Nullable<decimal> TimeOfAssistance { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
