//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssistanceManagerEntities2 : DbContext
    {
        public AssistanceManagerEntities2()
            : base("name=AssistanceManagerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Asset { get; set; }
        public virtual DbSet<Assistance> Assistance { get; set; }
        public virtual DbSet<AssistanceDetail> AssistanceDetail { get; set; }
        public virtual DbSet<AssitanceStatus> AssitanceStatus { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractAssets> ContractAssets { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<SU00_LoginType> SU00_LoginType { get; set; }
        public virtual DbSet<SU01_Login> SU01_Login { get; set; }
        public virtual DbSet<SU24_Authorizations> SU24_Authorizations { get; set; }
        public virtual DbSet<SU25_Roles> SU25_Roles { get; set; }
        public virtual DbSet<Technicians> Technicians { get; set; }
    }
}
