//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SU24_Authorizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SU24_Authorizations()
        {
            this.SU25_Roles = new HashSet<SU25_Roles>();
        }
    
        public string AuthTransaction { get; set; }
        public string AuthDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SU25_Roles> SU25_Roles { get; set; }
    }
}
